### ISSUE TITLE
Network Load Balancer Backend and other errors during deployment

### ISSUE THREAD

**Issue by mirlanimash** [egorshulga/oci-always-free-k8s#1]
I had following errors during the deployment through terraform apply:

![1st_Part](https://user-images.githubusercontent.com/84252011/151735748-4a4f65a1-3659-4564-b99c-dd33c4d1680e.jpg)
![2nd_Part](https://user-images.githubusercontent.com/84252011/151735759-bf4525a3-62b3-4ef8-885c-9f64a0a6064d.jpg)

**Comment by egorshulga** [comment]
Thank you! I think I spotted this 'Invalid state transition' error once. I guess it appears because we need to create _lots_ of resources underneath NLB, and Oracle performs it in a sequential order. Manual retry will definitely help with this one (and I think I'll need to add this issue to troubleshooting section in readme).

I guess I missed the fact, that there could be no `scp` tool on machine where the script is run. We use it to [copy some configs](https://github.com/egorshulga/oci-always-free-k8s/blob/7134a4c82bd5122e0096955df2b2dd7d89f1e932/k8s/control-plane.tf#L71) from leader node after control-plane has setup.
As a quick fix you may try to install the `scp` tool. And let me think for a moment, how we should copy files from the remote (to make a proper fix). I think there exists a terraform provider for it

**Comment by egorshulga** [comment]
@mirlanimash I guess it should be better now. Now scripts use [remote_file](https://registry.terraform.io/providers/tenstad/remote/latest/docs/data-sources/file) instead of `scp`.

Could you please try once again and let me know whether it's working for you?

**Comment by laguten** [comment]
I have a similar error, although scp is installed. Three repeated attempts does not lead to the desired result.

![2022-01-31_16_22_09](https://user-images.githubusercontent.com/10452157/151820821-12aa3fb3-f638-4402-af16-28ca4f718c98.png)

**Comment by egorshulga** [comment]
@laguten could you please try with the latest code? Scp is no longer required.

(Though I think the error with the previous code occurred because scp errors when a directory for an output file does not exist. I think that I was trying to create it, but mkdir statement that I used was for Windows os, and it's hard to support Linux in a single command. Anyway, it should not be an issue with the latest code, as it no longer depends on scp)

**Comment by mirlanimash** [comment]
Used git stash, git pull, git stash pop.
At first application had that same error N409. But remote-exec, local-exec worked fine with @egorshulga 's modifications. Since the error was telling to try later and @egorshulga explained above that oci creates resources sequentially, waited around 5 mins and tried again, and voila:

![Success](https://user-images.githubusercontent.com/84252011/151859809-4ac95df0-7408-4fe7-a193-dffcac99e0f8.jpg)

![InstancesOnOCI](https://user-images.githubusercontent.com/84252011/151860314-f728d957-791d-43e7-b470-21a7e843d7b5.jpg)


Gonna play around. Need to install kubectl to Windows first.

Great job @egorshulga . Gonna let my friends and colleagues know about this awesome project.

**Comment by egorshulga** [comment]
Thank you @mirlanimash!

Let me close this issue for now. Please ping me if you spot anything that could be further improved in the scripts
